"""initial

Revision ID: 002c8c58f70a
Revises: 
Create Date: 2026-06-11 21:53:22.856005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002c8c58f70a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age_group', sa.String(length=10), nullable=True),
    sa.Column('signup_date', sa.Date(), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('last_order_date', sa.Date(), nullable=True),
    sa.Column('preferred_channel', sa.String(length=20), nullable=True),
    sa.Column('preferred_categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('segments',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('nl_query', sa.Text(), nullable=True),
    sa.Column('filter_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('segment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('trend_context', sa.Text(), nullable=True),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('category_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_learnings',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('segment_description', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('message_style', sa.String(length=30), nullable=True),
    sa.Column('open_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('click_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('order_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communications',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('variant_id', sa.String(length=5), nullable=True),
    sa.Column('personalized_message', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_attributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attributed_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communications')
    op.drop_table('campaign_learnings')
    op.drop_table('orders')
    op.drop_table('campaigns')
    op.drop_table('segments')
    op.drop_table('customers')
    # ### end Alembic commands ###
